# Generated by Django 3.2.8 on 2021-10-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
